### ISSUE TITLE
Dependency encoding new

### ISSUE THREAD

**Issue by twuebi** [stickeritis/sticker-encoders#15]
I am writing pyo3 bindings to replace my `sticker-python` fork by some bindings around this crate (no more need for a tensorflow stub, yay!). 

Right now I am facing the issue that the `new` methods of the dependency encodings are crate intern, could they be lifted to pub?

**Comment by danieldk** [comment]
I think so! Feel free to do a PR :).

**Comment by twuebi** [comment]
#16
